// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Index(Props) {
  return React.createElement("div", undefined, React.createElement("h1", undefined, "Welcome to my ReScript website!"));
}

var make = Index;

export {
  make ,
}
/* react Not a pure module */
